FROM jlesage/baseimage-gui:ubuntu-24.04-v4.7.1

ENV APP_NAME="typora_en"
ENV NOVNC_LANGUAGE="en_US"
ENV HOME=/config
ENV LC_ALL=C

COPY --chmod=755 startapp_en.sh /startapp.sh

# install typora
RUN apt update 
RUN apt install -y wget libasound2t64 libgbm1 libgtk-3-0t64 libdrm2 libcups2t64 libatk-bridge2.0-0t64 libatk1.0-0t64 libglib2.0-0 libnss3 libdbus-1-3
RUN wget -O /tmp/typora_linux_amd64.deb $(wget -qO- https://typora.io/#linux | grep -oP '(?<=href=")[^"]+\.deb')
RUN apt install -y /tmp/typora_linux_amd64.deb

# get typora version
RUN dpkg-deb -I /tmp/typora_linux_amd64.deb | grep Version | awk '{print $2}' > /var/typora_version.txt 

RUN apt-get autoclean
RUN rm -rf /var/lib/apt/lists/*
RUN rm /tmp/typora_linux_amd64.deb

