FROM jlesage/baseimage-gui:ubuntu-24.04-v4.7.1

ENV APP_NAME="typora_zh"
ENV NOVNC_LANGUAGE="zh_Hans"
ENV TZ=Asia/Shanghai
ENV HOME=/config
ENV LANG=zh_CN.UTF-8
ENV LANGUAGE=zh_CN:zh
ENV LC_ALL=zh_CN.UTF-8

COPY --chmod=755 index.html.zh /opt/noVNC/index.html
COPY --chmod=755 startapp_zh.sh /startapp.sh

# 安装中文字体和locale配置
RUN apt update 
RUN apt install -y locales fonts-noto-cjk 
RUN sed -i '/^#\s*zh_CN\.UTF-8 UTF-8/s/^#\s*//' /etc/locale.gen
RUN locale-gen

# 安装搜狗输入法
RUN apt install -y fcitx fcitx-googlepinyin
ENV XMODIFIERS=@im=fcitx
ENV GTK_IM_MODULE=fcitx
ENV QT_IM_MODULE=fcitx

# 安装typora
RUN apt install -y wget libasound2t64 libgbm1 libgtk-3-0t64 libdrm2 libcups2t64 libatk-bridge2.0-0t64 libatk1.0-0t64 libglib2.0-0 libnss3 libdbus-1-3
RUN wget -O /tmp/typora.html https://typoraio.cn/#linux
RUN wget -O /tmp/typora_linux_amd64.deb $(grep -oP '(?<=href=")[^"]+amd64\.deb' /tmp/typora.html|head -1)
RUN apt install -y /tmp/typora_linux_amd64.deb

# 设置图标
COPY ./icon/typora.png /tmp/typora.png
RUN install_app_icon.sh /tmp/typora.png

# 获取typora版本号
RUN dpkg-deb -I /tmp/typora_linux_amd64.deb | grep Version | awk '{print $2}' > /var/typora_version.txt 

RUN apt-get autoclean
RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf /tmp/* 
